# Generated by Django 4.0.3 on 2023-04-06 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0002_exam_virtual_examinee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualUserId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_user_id', models.CharField(max_length=100)),
                ('create_date', models.DateField()),
                ('examinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
