# Generated by Django 4.0.3 on 2023-04-06 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_virtualuserid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VirtualUserId',
            new_name='VirtualUser',
        ),
    ]
